version: "3.6"

services:
  lab1:
    build: ./lab1
    restart: 'unless-stopped'
    ports:
      - "8011:80"
    volumes: 
      - ./lab1/src/:/var/www/html/
  lab2:
    build: ./lab2
    restart: 'unless-stopped'
    ports:
      - "8012:80"
    volumes: 
      - ./lab2/src/:/var/www/html/
  lab3:
    build: ./lab3
    restart: 'unless-stopped'
    ports:
      - "8013:80"
    volumes: 
      - ./lab3/src/:/var/www/html/
