version: "3.6"
services:
    db:
        build: ./database
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password

    lab1:
        build: ./lab1
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./lab1/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab2:
        build: ./lab2
        restart: unless-stopped
        ports:
            - 8002:80
        volumes:
            - ./lab2/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab3:
        build: ./lab3
        restart: unless-stopped
        ports:
            - 8003:80
        volumes:
            - ./lab3/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password