version: "3.6"
services:
    db:
        build: ./database
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password

    lab1:
        build: ./lab1
        restart: unless-stopped
        ports:
            - 8071:80
        volumes:
            - ./lab1/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab2:
        build: ./lab2
        restart: unless-stopped
        ports:
            - 8072:80
        volumes:
            - ./lab2/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab3:
        build: ./lab3
        restart: unless-stopped
        ports:
            - 8073:80
        volumes:
            - ./lab3/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab4:
        build: ./lab4
        restart: unless-stopped
        ports:
            - 8074:80
        volumes:
            - ./lab4/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab5:
        build: ./lab5
        restart: unless-stopped
        ports:
            - 8075:80
        volumes:
            - ./lab5/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab6:
        build: ./lab6
        restart: unless-stopped
        ports:
            - 8076:80
        volumes:
            - ./lab6/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab7:
        build: ./lab7
        restart: unless-stopped
        ports:
            - 8077:80
        volumes:
            - ./lab7/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    lab8:
        build: ./lab8
        restart: unless-stopped
        ports:
            - 8078:80
        volumes:
            - ./lab8/src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password

